package ghidra.mcp.prompts;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

import ghidra.mcp.McpPromptRegistry;
import io.modelcontextprotocol.spec.McpSchema.GetPromptResult;
import io.modelcontextprotocol.spec.McpSchema.Prompt;
import io.modelcontextprotocol.spec.McpSchema.PromptMessage;
import io.modelcontextprotocol.spec.McpSchema.Role;
import io.modelcontextprotocol.spec.McpSchema.TextContent;

public class BatchHelpPrompt {

    public Prompt getPromptDef() {
        return new Prompt(
            "batch_mode_help",
            "Provides instructions and examples for using the execute_batch tool.",
            Collections.emptyList() // No arguments
        );
    }

    public Function<Map<String, String>, GetPromptResult> getHandler() {
        return args -> {
            String helpText = """
                # Batch Execution Tool Help

                The `execute_batch` tool allows you to run multiple MCP tools sequentially within a single Ghidra transaction. This ensures that all changes are applied atomically (all or nothing) and reduces network latency.

                ## Usage
                Call `execute_batch` with a `requests` argument, which is a list of tool calls.

                ## Example
                To rename a function and add a comment at the same time:

                ```json
                {
                  "requests": [
                    {
                      "tool": "set_label",
                      "args": {
                        "address": "0x00401234",
                        "name": "process_input"
                      }
                    },
                    {
                      "tool": "set_comment",
                      "args": {
                        "address": "0x00401234",
                        "comment": "Renamed after analysis of input handling"
                      }
                    }
                  ]
                }
                ```

                ## Notes
                - If any step fails, the entire transaction is rolled back.
                - You cannot call `execute_batch` recursively.
                - This is the preferred method for applying complex refactorings generated by the LLM.
                """;

            return new GetPromptResult(
                "batch_mode_help",
                List.of(new PromptMessage(Role.USER, new TextContent(helpText)))
            );
        };
    }

    public void register(McpPromptRegistry registry) {
        registry.register(getPromptDef(), getHandler());
    }
}
